/**
 * Created by Greg on 4/12/2016.
 */
module.exports = {
  attributes: {
    //probably auto-generated by Mongo
    // uuid: {
    //   type: 'integer',
    //   primaryKey: true,
    //   unique: true
    // },

    title: {
      type: 'string',
      size: '50',
      defaultsTo: ''
    },

    description: {
      type: 'mediumtext',
      defaultsTo: ''
    },

    datePosted: {
      type: 'integer',
      defaultsTo: 0
    },

    tags: {
      type: 'array',
      defaultsTo: []
    },

    // user: {
    //   model: 'User'
    // }

    // skills: {
    //   collection: 'Property'
    // }

    // category: {
    //   model: 'Category'
    // }

    active: {
      type: 'boolean',
      defaultsTo: true
    }
  }
};
